### PR TITLE
Full mapper support

### PR DESCRIPTION
**Pull request by mvmcjr**
I moved the mapper stuff to a separate library (Proxier) and removed the mask stuff too, I think this is ready to pull, but I'll run some tests first.

### CODE REVIEW

**Comment by rc201612** [comment]
Getting the below error when I try and run these changes. Have I missed something?

Method not found: 'Void Proxier.Mappers.Mapper.InitializeMapperClasses(Ninject.IKernel)'.

**Comment by mvmcjr** [comment]
@rc201612 Just got home, will test it out right now

**Comment by mvmcjr** [comment]
@rc201612 Found it, uploading as we speak

**Comment by mvmcjr** [comment]
@rc201612 Unfortunately my VSTS free hours have run out, so we'll have to wait for nuget to validate the package. I'll have dinner and try to move to AppVeyor. You can follow the progress here: https://www.nuget.org/packages/Proxier/1.2.0

**Comment by wobbince** [comment]
@redbaty there is no immediate rush. Take your time. I just thought I'd have a play with it.

**Comment by mvmcjr** [comment]
@wobbince  @rc201612 This should be fixed in b8001d0d7620315c5335563d4d47d1c9df2591d9 ! Thanks for the feedback, I get so excited lol 😄

**Pull request merged**
