### PR TITLE
Mask and mapper

### PR DESCRIPTION
**Pull request by mvmcjr**
Sorry I had to put these two together, but since this is a re-creation of the commits I had already made, git couldn't help me out 😢

### CODE REVIEW

**Comment by mvmcjr** [comment]
This one is "*too complex to resolve in the web editor*", so I'll review this tomorrow.

**Comment by mvmcjr** [comment]
@EdonGashi I was trying to merge this in my fork, and I noticed that this is incompatible with the new replacement pipe so this will take a little more time.

**Comment by edongashi** [comment]
Dont worry, masking is not wpf native anyway so its not a big priority.

**Comment by mvmcjr** [comment]
@EdonGashi Thinking about it this doesn't seem so necessary, I might remove it from this branch and re-visit it in the future, cause the mapper feature is really cool! Oh and I've just sent you the VSTS invitation.

**Comment by edongashi** [comment]
Plus it adds some new package references, right? There are already 2 major toolkits we're using, so we might not bloat it too much. Accepted the inv, I'll check the setup when I'm at a computer. Thanks

**Comment by mvmcjr** [comment]
@EdonGashi Yeah, but the WPF Extensions package is open-source so I'll try to strip the Masked textbox out of it cause their Mask format is really easy and efficient. Hopefully I'll do it this weekend

**Pull request merged**
